Clean code for real life branch
project-neon/NeonFC pull request #121
Opened 2023-01-25 14:34 UTC by makitayukio

2023-01-25 18:29 UTC, jpkleal requested changes
A função update da classe SimpleLQR está com um '_' a mais.
Se possível mover o arquivo PID_test.py da pasta strategy/rsm2022 para a pasta strategy/tests

2023-01-25 18:59 UTC, GaMendes commented on comm/rl_comm.py
>          # battery = self.comm.readline().decode('ascii')
Se não ta usando, tira

2023-01-25 19:00 UTC, GaMendes commented on comm/rl_comm.py
>                  # }
Se não ta usando, tira

2023-01-25 19:02 UTC, GaMendes commented on commons/math.py
>          return 0
Tem dois `return` no mesmo nível do código. Um deles é com certeza desnecessário.

2023-01-25 19:03 UTC, GaMendes commented on commons/math.py
>      """ Returns the unit vector of the vector."""
Comentário em inglês, e ali em cima ta tudo em português. Matenham um único idioma sempre que possível.

2023-01-25 19:04 UTC, GaMendes commented on commons/math.py
>  def speed(_list, _fps):
O que essa função retorna?

2023-01-25 19:05 UTC, GaMendes commented on commons/math.py
>  def distance(A, B, P):
Qual a diferença dessa função para a função `dist_point_line`, se elas fazem a mesma coisa com tipos de parâmetros diferentes, é legal manter um padrão na nomenclatura delas. Python deve ter polimorfismo, da uma olhada nisso.

2023-01-25 19:07 UTC, GaMendes commented on commons/math.py
>    return math.acos(dotproduct(v1, v2) / (length(v1) * length(v2)))
Essa função `dotproduct` foram vocês que criaram? Pq se sim, ela não segue o padrão do código de usar "_" para separar nomes compostos.

2023-01-25 19:11 UTC, GaMendes commented on commons/math.py
>  def dist_point_line(x1, y1, x2, y2, x3, y3):
Ali embaixo tem outra função que aparentemente faz a mesma coisa `distance_to_line(x, y, l1x, l1y, l2x, l2y)`. Qual a diferença?

2023-01-25 19:12 UTC, GaMendes commented on controller/PID.py
>          # self.pid_file.write(str() + "," + str(now_linear) + "," + str(vl) + "," +  str(self.angular_desired) + "," + str(now_angular) + "," + str(0) + '\n')
Não ta usando? Remove

2023-01-25 19:13 UTC, GaMendes commented on controller/PID_control.py
>          # self.pid_writer = Writer('pid',
Não ta usando? Remove

2023-01-25 19:15 UTC, GaMendes commented on controller/PID_control.py
>          # if(abs(alpha) > math.pi/2):
Não ta usando, remove

2023-01-25 19:15 UTC, GaMendes commented on controller/PID_control.py
>          # self.pid_writer.write([self.KP, self.KI, self.KD, gamma, alpha, w])
Não ta usando, remove

2023-01-28 15:46 UTC, makitayukio commented on commons/math.py
>  def speed(_list, _fps):
Essa função é usada pra calcular a velocidade da entidade (Robô, Bola) usando os dados que recebemos da visão (fps e frames).

2023-01-28 15:54 UTC, makitayukio commented on commons/math.py
>  def dist_point_line(x1, y1, x2, y2, x3, y3):
Lendo o código não entendi a diferença, mas fiz um teste aqui com os mesmos parâmetros pros dois e retornaram valores diferentes. Então não tenho ideia.

2023-01-28 15:57 UTC, makitayukio commented on commons/math.py
>  def dist_point_line(x1, y1, x2, y2, x3, y3):
Vendo aqui pelas ocorrências, cada função é usada pra casos diferentes, essa é usada no Dijkstra e o segundo é usado no UVF attacker.

2023-02-13 17:14 UTC, merged