Implementação do algoritmo A*
project-neon/NeonFC pull request #45
Opened 2021-05-27 00:00 UTC by Ana-Monici

2021-05-29 20:14 UTC, GaMendes commented on algorithims/a_star/astarTest.py
> +        # self.open_set.update(FieldGraph().graph/nodes)
Se não ta usando, tira do código

2021-05-29 20:14 UTC, GaMendes commented on algorithims/a_star/astarTest.py
> +            # self.open_list.remove(current)
Se não ta usando, tira do código

2021-05-29 20:31 UTC, Alexsandr0x commented on algorithims/a_star/astarTest.py
> +        # self.open_set.update(FieldGraph().graph/nodes)
Acredito que isso sera removido apos sair de WIP

2021-06-11 02:20 UTC, Alexsandr0x requested changes
O codigo esta muito limpo, ficou otimo!

as sugestoes levantadas devem ser feitas, nome de arquivo com ```test``` induz ao erro e esse exemplo ai tbm pode causar problemas se estiver em codigo.

2021-06-11 02:20 UTC, Alexsandr0x commented on algorithims/a_star/fieldGraph.py
> +class FieldGraph():
@Ana-Monici como eu implementaria aqui se tivesse uma heusristica externa? a ideia eh que usemos ```FieldGraph``` como uma classe abstrata ou exemplo certo?

Se for assim, recomendo que esse exemplo esteja em outro lugar (pode ser numa documentacao na wiki, por exemplo), por que ele nao faz parte do funcionamento do sistema. Tambem, podemos dar o exemplo ja implementando num modulo de strategy, como foi feito [aqui para os campos potencias](https://github.com/project-neon/NeonFC/blob/master/strategy/tests/pfScratch.py).

2021-06-11 02:20 UTC, Alexsandr0x commented on algorithims/a_star/astarTest.py
> +import numpy
O nome desse arquivo nao precisa ser mais ```astarTest```. Ate porque ele nao sera mais um teste quando estiver na branch principal

2021-06-15 11:16 UTC, GaMendes reviewed
No geral tbm acho que ta muito bom.

2021-06-15 11:16 UTC, GaMendes commented on algorithims/a_star/astarTest.py
> +    # Considering pos = [x, y] or pos = (x, y)
Esse comentário não ta muito claro pra mim, pelo que eu vi pela implementação, vc ta recebendo `pos1` e `pos2``como listas não?

2021-06-15 11:16 UTC, GaMendes commented on algorithims/a_star/astarTest.py
> +    d = numpy.sqrt(((x2-x1)**2 + (y2-y1)**2))
Troca esse `d` pela palavra toda `distance`, ou se vocês preferirem, retorna a conta direto.

2021-06-15 11:16 UTC, GaMendes commented on algorithims/a_star/astarTest.py
> +    d = numpy.sqrt(((x2-x1)**2 + (y2-y1)**2))
Essa conta tem uns parênteses desnecessários tbm

2021-06-16 23:40 UTC, Alexsandr0x approved these changes

2021-06-16 23:40 UTC, merged