feat/positions
project-neon/NeonFC pull request #48
Opened 2021-06-25 23:35 UTC by Yukio325

Added pyVSSSReferee usage to send position replacements to referee.

2021-06-25 23:40 UTC, Yukio325 commented on entities/coach/larc2020.py
> +        replacements = foul.get(team_color, 0)
```suggestion
        replacements = foul.get(team_color, foul.get("POSITIONS"))
```

2021-06-25 23:42 UTC, Yukio325 commented on entities/coach/larc2020.py
> +            replacements = foul.get("POSITIONS")
```suggestion
        replacements = foul.get(team_color, foul.get("POSITIONS"))
```

2021-06-26 20:34 UTC, Alexsandr0x requested changes

2021-06-26 20:34 UTC, Alexsandr0x commented on main.py
> +        self.referee = RefereeComm(config_file = "config.json")
Esse ```config.json``` deveria ser o mesmo que o NeonFC inicializa, ou algum outro parametrizado, caso contrario se o ambiente mudar de uma partida para outra teremos problemas

2021-06-26 20:34 UTC, Alexsandr0x commented on main.py
> +        print(self.match.team_color)
Evite prints de debug na branch principal

2021-06-27 19:10 UTC, GaMendes approved these changes

2021-06-28 14:24 UTC, Alexsandr0x approved these changes

2021-06-28 14:25 UTC, merged